### ISSUE TITLE
Support JWT signing for Stacks authentication

### ISSUE THREAD

**Issue by kyranjamie** [Zondax/ledger-blockstack#102]
[As mentioned in Slack](https://hiropbc.slack.com/archives/C01FSJYT64S/p1649320050868969), in order for the Stacks Ledger integration to be compatible with the Stack authentication flow, a JWT payload needs to be signed by a key on the "identities keychain", the `m/888'/0'` derivation path.

This feature would need to accept a JWT payload and return a signature.

The implementation would need to function the same as our [TypeScript implementation found here](https://github.com/stacks-network/jsontokens-js/blob/master/src/signer.ts#L36-L117).

- Is the device capable of handing and signing a JWT?
- How large of an effort would this be to implement?

**Comment by neithanmo** [comment]
@kyranjamie i opened a [PR](https://github.com/Zondax/ledger-blockstack/pull/104), can you take a look. it omits network version and returns a publicKey using the path you described above.

**Comment by markmhx** [comment]
@neithanmo To be clear, the PR you've linked above (https://github.com/Zondax/ledger-blockstack/pull/104) resolves this particular issue (for complete JWT signing) or simply the one that Kyran has linked (#103, for passing a m/888' leading derivation path as a preliminary fix)?

**Comment by neithanmo** [comment]
> @neithanmo To be clear, the PR you've linked above (#104) resolves this particular issue (for complete JWT signing) or simply the one that Kyran has linked (#103, for passing a m/888' leading derivation path as a preliminary fix)?

it fixed the issue with the new derivation path. which is required by the JWT feature. later this week will open a PR with the full JWT support.

**Comment by neithanmo** [comment]
closed via #111
