### ISSUE TITLE
NPM published version is different than github

### ISSUE THREAD

**Issue by hstove** [Zondax/ledger-blockstack#115]
On [npm](https://www.npmjs.com/package/@zondax/ledger-blockstack), the published version is 0.24.0. However, in this repo, the version in package.json (https://github.com/Zondax/ledger-blockstack/blob/main/js/package.json#L3) is 0.22.5. Why the difference in versions?

:link: [zboto Link](https://app.clickup.com/t/2gferjp)

**Comment by neithanmo** [comment]
The version mismatch was a typo when creating the js package release, which is done manually. it is now fixed and an updated version has been uploaded to npm.
