### ISSUE TITLE
Limitation (number of postconditions)

### ISSUE THREAD

**Issue by jleni** [Zondax/ledger-blockstack#2]
Due to memory constraints, we have limited the number of postconditions:

https://github.com/Zondax/ledger-blockstack/pull/1#discussion_r442493846

Can you confirm that this limit is acceptable? or please suggest a number that would be adequate.

**Comment by kantai** [comment]
This limit should be acceptable. What would be the impact of doubling this to 16? (Would that exceed the memory limits on the ledger?)
