### ISSUE TITLE
Add µSTX suffix to micro STX amounts displayed on device

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#36]
As suggested by @kyranjamie with https://github.com/blockstack/stacks-wallet/issues/291#issuecomment-715261332, the user will understand the micro STX amount displayed on their Ledger device more easily if the µSTX suffix is provided. 

Otherwise, they could perhaps confuse it easily with whole STX values.

**Comment by kyranjamie** [comment]
This affects all mentions of currency units on the device: amount and fee, off the top of my head. 

If unicode character `µ` is not supported, a lowercase `u` will suffice. `Fee uSTX`

**Comment by jleni** [comment]
@kyranjamie is it only Fee that need to be marked as uSTX?

**Comment by kyranjamie** [comment]
@jleni No, both amount and fee should be marked as uSTX
