### ISSUE TITLE
Verify the structure of STX token transfer payload

### ISSUE THREAD

**Issue by neithanmo** [Zondax/ledger-blockstack#4]
According to the [documentation](https://github.com/blockstack/stacks-blockchain/blob/acc13a0e7bf14ea8372c75978e9056729747f028/sip/sip-005-blocks-and-transactions.md#transaction-encoding) for Transaction payloads:

A STX token-transfer payload is encoded as follows:
- A recipient address, comprised of a 1-byte address version number and a 20-byte public key hash that identifies a (possibly unmaterialized) standard account to receive the tokens,
- An 8-byte number denominating the number of microSTX to send to the recipient address's account.

We realized that there is a third field called MEMO, according to this [issue](https://github.com/blockstack/stacks-blockchain/issues/1193). this rises the next questions:

1. Is this field optional? if so, there is a byte that indicates whether this value is present or not?
2. Looking at the test in [here](https://github.com/blockstack/stacks-blockchain/blob/master/src/chainstate/stacks/transaction.rs#L1407), seems that the MEMO field is always present, but the final encoding does not follow the one stated in the documentation, for example, following the same test in the link above, we see:
```
        let tt_stx = TransactionPayload::TokenTransfer(addr.clone(), 123, TokenTransferMemo([1u8; 34]));

        // wire encodings of the same
        let mut tt_stx_bytes = vec![];
        tt_stx_bytes.push(TransactionPayloadID::TokenTransfer as u8);
        addr.consensus_serialize(&mut tt_stx_bytes).unwrap();
        tt_stx_bytes.append(&mut vec![0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 123]);
        tt_stx_bytes.append(&mut vec![1u8; 34]);
```
the tt_stx_bytes is the encoded token-transfer payload, which content is:
`[0, 5, (1-byte addrs version, Hash160), 8-bytes-amount, [u8; 34(MEMO)]]`
lets focus on the first 2 bytes, If we follow the documentation, those 2 bytes should be:
- 0x00 => Indicating it is a token transfer payload
- 0x00 or 0x01? => Indicating it is an STX token-transfer payload 

so that the question is, what does the 0x05 byte identifier mean??

**Comment by kantai** [comment]
> Is this field optional? if so, there is a byte that indicates whether this value is present or not?

No -- the memo field is always present in the transaction.

> ``` [0, 5, (1-byte addrs version, Hash160), ...] ```

The first byte indicates that the payload is a token transfer. The only native token transfer operation is a STX token transfer. The second byte is part of the serialization of the recipient address -- 0x05 indicates that it is a "standard recipient", 0x06 indicates a "contract recipient". See the documentation here: https://github.com/blockstack/stacks-blockchain/blob/master/sip/sip-005-blocks-and-transactions.md#transaction-payloads-1, which was updated in April (the link you provided is an old commit).

**Comment by neithanmo** [comment]
Did not realize it was a previous commit. Thank you, It clarifies a lot.
