### ISSUE TITLE
Prevent freezing issue reported by Ledger

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#43]
[Per @nndiaye-ledger in Slack](https://ledger-dev.slack.com/archives/G013HKZRC3X/p1610355838062600): "I have a freezing issue as I can't navigate through the menus or quit the app"

Requested for diagnosis:

- some description of the steps you follow that lead to the problem?
- ideally the actual transaction blob that results in the freeze (so we can avoid going through the webapp, etc.)

**Comment by nndiaye-ledger** [comment]
Stacks nano app version: 0.10.2
Nano S firmware version : 1.6.1

Flow: 

1. Enter Stacks app
2. Acknowledge "Pending legder review" message 
3. Arrive in landing menu with  " Stacks Do not use " message 
4. App freezes with no possibility to navigate or quit the app

However, we receive on device all prompts for validation and verification( address, transactions )

**Comment by markmhx** [comment]
Thanks! cc @jleni ☝️

**Comment by jleni** [comment]
We had this reported in the past. 
It is related to the "Pending legder review" message that Ledger introduces while they are running the review. That's the reason we never see that.
The "fix" used to be a minor configuration setting that an engineer from Ledger recommended.
I will check with him and resolver this later today.
