### ISSUE TITLE
Fix icon shown on home screen of Ledger device with white background

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#44]
As requested by @nndiaye-ledger in Slack, the STX logo should have a white background like the others:

![1610373185234](https://user-images.githubusercontent.com/28991/104191793-434ffe00-541e-11eb-8cda-5c6c96fb38ca.jpg)

cc @jleni

**Comment by markmhx** [comment]
@jleni do you have the asset you need here or should @jasperjansz produce one?

**Comment by jleni** [comment]
yes, we would need the asset, is that possible?

**Comment by markmhx** [comment]
Yep, I'll work with @jasperjansz on it now. Stay tuned.

**Comment by markmhx** [comment]
Here you go!

![stx-ledger-white](https://user-images.githubusercontent.com/28991/104197490-60d49600-5425-11eb-9794-68330ee2ca2b.gif)

**Comment by markmhx** [comment]
New asset that may work better:

![icon2](https://user-images.githubusercontent.com/28991/104299487-929d3980-54c5-11eb-8d05-0a5438fde860.gif)
