### ISSUE TITLE
Fix Ledger Nano X support for sending transactions

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#48]
We've gotten reports in Discord that users can authenticate to the Stacks Wallet v4.0.2 with Ledger Nano X but cannot subsequently send transactions successfully.

Ledger's redeployment of the Stacks app for provider 1 instead of 4 doesn't appear to have resolved this issue.

**Comment by markmhx** [comment]
Sending hangs for me upon confirming the transaction on my Ledger Nano X with Stacks Wallet v4.0.2 at this point in the experience:

![image](https://user-images.githubusercontent.com/28991/105024668-a65c1900-5a4c-11eb-8f86-aa654c85b060.png)

**Comment by jleni** [comment]
As discussed in Slack and to facilitate debugging on our side:

- The Ledger app itself is not hanging.. it remains active, however when the user clicks "Accept" there is no action, the click seems to be ignored.
- If the user clicks reject. The app responds correctly.
-
