### ISSUE TITLE
Update name in Ledger Live to "Stacks (STX)"

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#51]
It's unclear just what needs to be done to make this happen, but we'd like the Stacks app for Ledger Live to have the name "Stacks (STX)" instead of just "Stacks" so that users can search by "stx" and see it in the results for installation.

This is similar to how other tokens show the currency ticker in their listings.

@jleni has read that it's something in the configuration file for Ledger Live.

<img width="698" alt="Screen Shot 2021-01-22 at 14 28 28" src="https://user-images.githubusercontent.com/28991/105496714-25a45380-5cbe-11eb-84c1-dd874c984034.png">

<img width="349" alt="Screen Shot 2021-01-22 at 14 28 39" src="https://user-images.githubusercontent.com/28991/105496709-24732680-5cbe-11eb-9c1f-40ba6e1c608e.png">

**Comment by jleni** [comment]
As explained by Gaetan:

> for example, for the Ethereum (ETH) entry in Manager,
the app name is Ethereum
we lookup in our “@ledgerhq/cryptoassets” library a cryptocurrency that correspond to managerAppName = "Ethereum" , we find ethereum, we take the .ticker   https://github.com/LedgerHQ/ledgerjs/blob/master/packages/cryptoassets/src/currencies.js#L974
{{appName}} ({{ticker}})  formatted if a currency was found, otherwise fallback to just {{appName}}
We try to put all the currencies in this library as soon as there is an app for it (regardless of if Ledger Live support it)
but the ticker must not be part of the app. (edited) 

To fix this issue we need to send a PR to https://github.com/LedgerHQ/ledgerjs

**Comment by jleni** [comment]
we need to add something similar this:

https://github.com/LedgerHQ/ledgerjs/blob/01f9281d5df9dec2131ef5d9b5f73a6ee2b72294/packages/cryptoassets/src/currencies.js#L1008-L1026

for `stacks`

**Comment by jleni** [comment]
The `managerAppName` comes from here:

https://github.com/Zondax/ledger-blockstack/blob/91a5a75181316182d4ba79fc7a2ad9dc410908d1/app/Makefile#L58

**Comment by emmanuelm41** [comment]
This is the new currency I will send in the PR. What does it look like?


  stacks: {
    type: "CryptoCurrency",
    id: "stacks",
    coinType: 539,
    name: "stacks",
    managerAppName: "Stacks",
    ticker: "STX",
    scheme: "stacks",
    color: "#000",
    family: "stacks",
    units: [
      {
        name: "STX",
        code: "STX",
        magnitude: 8,
      },
    ],
    explorerViews: [],
  }

**Comment by emmanuelm41** [comment]
PR on LedgerHQ
[https://github.com/LedgerHQ/ledgerjs/pull/562](url)

**Comment by emmanuelm41** [comment]
PR on LedgerHQ

[https://github.com/LedgerHQ/ledgerjs/pull/562](url)

**Comment by markmhx** [comment]
Thanks @emmanuelm41!

**Comment by emmanuelm41** [comment]
The PR was approved. We should have this issue fixed. Can you confirm that @markmhx?

**Comment by markmhx** [comment]
I'm still seeing just "Stacks" in search results personally:

![image](https://user-images.githubusercontent.com/28991/106273445-fb5d1380-6232-11eb-8794-d8ffdd939110.png)

**Comment by markmhx** [comment]
@emmanuelm41 Any updates here? I'm still seeing the app listed without the ticker.

**Comment by jleni** [comment]
The change was accepted by Ledger 2 weeks ago, however, it depends on their release schedule when it will appear in a released version. I think the best option is to ping them in their Slack.

**Comment by markmhx** [comment]
I see the change now having updated my version of Ledger Live:

<img width="452" alt="Screen Shot 2021-02-16 at 12 31 48" src="https://user-images.githubusercontent.com/28991/108057540-101f1100-7053-11eb-834c-1328c46c2554.png">
