### ISSUE TITLE
Publish @zondax/ledger-blockstack to npm 

### ISSUE THREAD

**Issue by kyranjamie** [Zondax/ledger-blockstack#63]
Latest changes from https://github.com/Zondax/ledger-blockstack/pull/55 are not yet on npm

**Comment by jleni** [comment]
@emmanuelm41 can we integrrate our new way of publishing packages "npm_v..." here too?

**Comment by emmanuelm41** [comment]
Yes, sure! I will do that in a new brach and create de PR
