### ISSUE TITLE
Message signing

### ISSUE THREAD

**Issue by kyranjamie** [Zondax/ledger-blockstack#76]
Hiro wants to support message signing and verification in its wallets, [similar to the user flow described the MyCrypto wallet](https://support.mycrypto.com/how-to/getting-started/how-to-sign-and-verify-messages-on-ethereum). Ledger device support is needed to offer parity between our software and hardware wallets. 

The feature has been discussed in context of Hiro's wallet https://github.com/blockstack/stacks-wallet-web/issues/1051, and the Stacks blockchain https://github.com/blockstack/stacks-blockchain/issues/2693

Ultimately, we'd like support for structured data signing, like Ethereum's [EIP-721](https://eips.ethereum.org/EIPS/eip-712), though this task is scoped to prefixed bytestring message signing.

**Spec**
- The device should support prefixed bytestring message signing
  - Errors should be thrown for invalid content, or messages that would exceed the device's memory limits
- An ascii-encoded preview of the message should be printed on the device
  - Users can be warned or prohibited from passing too length content by wallet clients
- The readable prefix should be "Stacks Signed Message", with a similar formatting specification to EIP-712
- A new method, `sign`, should be added to the `@zondax/ledger-blockstack` package

These are relatively high-level requirements. If more details needed, let us know. We'll follow up with input from the blockchain team.

**Comment by jleni** [comment]
@kyranjamie can we close this issue?

**Comment by kyranjamie** [comment]
@jleni The only question I have pertains to the js lib. There haven't been any changes to it. How do we interface with/consume the new text signing method? Do we use the existing `sign` function exposed? This only accepts type `Buffer` currently, so, would we first need to convert strings?

**Comment by neithanmo** [comment]
> @jleni The only question I have pertains to the js lib. There haven't been any changes to it. How do we interface with/consume the new text signing method? Do we use the existing `sign` function exposed? This only accepts type `Buffer` currently, so, would we first need to convert string

Yes, You should use the sign function, there are no changes in the current interface as the parser internally will recognize the data as either a transaction or message. of course, the result of the parsing is shown on the screen for validation from the user before signing it the same as it is done for transactions.

**Comment by neithanmo** [comment]
closed via #82
