### ISSUE TITLE
Add better STX icon

### ISSUE THREAD

**Issue by markmhx** [Zondax/ledger-blockstack#79]
Right now the icon is different than our standardized one:

![image](https://user-images.githubusercontent.com/28991/139667170-8b6ab3c7-120c-42ba-9356-5f5487f306cf.png)

**Comment by markmhx** [comment]
@jleni can you help specify here what exact image format and dimensions, etc. are needed? We'll then provide the asset.

**Comment by neithanmo** [comment]
Hi @mark you can send us a **14x14 1-bit gif** image, using our communication channel. so we can update the icon.

**Comment by jleni** [comment]
@markmhx any updates on this?

**Comment by eugeniadigon** [comment]
Hi all,
Here's the 1-bit gif version of the logo

![Stacks-1bit](https://user-images.githubusercontent.com/78865845/152205529-9608d12a-947e-42e6-bdd3-11d45920468f.gif)

**Comment by neithanmo** [comment]
thanks @eugeniadigon  i will check if it works for us and then update it
